include: 'https://raw.githubusercontent.com/Sensirion/ci-config-github/master/github-status-gitlab-ci-template-v1.yml'

stages:
  - publish_build_pending
  - build
  - publish_build_status

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GITHUB_PROJECT_NAME: embedded-uart-sps

publish_build_pending:
  extends: .github_publish_pending
  stage: publish_build_pending

publish_success:
  extends: .github_publish_success
  stage: publish_build_status

publish_failure:
  extends: .github_publish_failure
  stage: publish_build_status

test:
  stage: build
  image:
    name: sensirion/embedded-ci:2.1.0
  tags: [linux, docker]
  script:
    - make prepare
    - make
    - make clean
    - make style-check
    - make release
    - (cd release/sps30-uart && make && make clean)
    - (cd release/sps30-uart && make uart_sources=sample-implementations/linux/sensirion_uart_implementation.c && make clean)
    - (cd release/sen44-uart && make && make clean)
    - (cd release/sen44-uart && make uart_sources=sample-implementations/linux/sensirion_uart_implementation.c && make clean)
